### ISSUE TITLE
TypeError: expected unicode, got str 

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [J535D165/recordlinkage#35]
Hi, I tried to run this 

`compare_cl.string('Address', 'Address', method='jarowinkler', threshold=0.85)` and getting this 

`TypeError: ('expected unicode, got str', u'occurred at index (93, 1934)')` Then thought its related to the underlying jellyfish issue - #https://github.com/jamesturk/jellyfish/issues/45, then tried the solution suggested there, but it didn't work. Can you please let me know if I have to convert the columns to unicode before hand?

**Comment by J535D165** [comment]
Hello,

The simple solution is: use Python 3

Option 2: df['Address'] = df['Address'].str.encode('utf-8') # or some other
encoding.

option 3: you do have mixed types in your column. Type set first.

The issue is related to https://github.com/jamesturk/jellyfish/issues/58.

Good luck


2017-06-05 8:56 GMT+02:00 Jeeva <notifications@github.com>:

**Comment by Jeeva-Ganesan** [comment]
Hi. This works. Thanks.

**Comment by IMXIAOYI** [comment]
those three options don't work for me. And my solution is to add 'encoding='utf8' in 'pandas.DataFrame.from_csv(path="salary.csv",index_col=None, encoding='utf8')
